namespace Agency.GraphRAG.Code.Query;

/// <summary>
/// The final output from the query pipeline.
/// </summary>
public sealed record QueryResponse
{
    /// <summary>Gets the synthesized answer text.</summary>
    public required string Answer { get; init; }

    /// <summary>Gets the query plan that drove retrieval.</summary>
    public required QueryPlan Plan { get; init; }

    /// <summary>Gets the assembled context used for synthesis.</summary>
    public required QueryContextAssembly Context { get; init; }

    /// <summary>Gets the raw retrieval result containing symbols and clusters.</summary>
    public QueryRetrievalResult? Retrieval { get; init; }

    /// <summary>Gets the duration of the classification (planning) stage.</summary>
    public TimeSpan ClassifyDuration { get; init; }

    /// <summary>Gets the duration of the retrieval stage.</summary>
    public TimeSpan RetrieveDuration { get; init; }

    /// <summary>Gets the duration of the context assembly stage.</summary>
    public TimeSpan AssembleDuration { get; init; }

    /// <summary>Gets the duration of the answer generation stage.</summary>
    public TimeSpan AnswerDuration { get; init; }

    /// <summary>Gets the number of input tokens used by the LLM, if available.</summary>
    public long? InputTokenCount { get; init; }

    /// <summary>Gets the number of output tokens generated by the LLM, if available.</summary>
    public long? OutputTokenCount { get; init; }
}
